# SPDX-FileCopyrightText: 2024 Shell Global Solutions International B.V. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: Building the package
on:
  push:
    branches:
      - 'main'
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build
      - name: Build the package
        run: |
          python -m build
      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: openmcmc_whl
          path: ./dist/*.whl
