# SPDX-FileCopyrightText: 2024 Shell Global Solutions International B.V. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: ManualBuild

permissions: write-all

on:
  workflow_dispatch:

jobs:
  Build:
    uses: sede-open/openMCMC/.github/workflows/build_package.yml@main
    secrets: inherit

  PublishDocs:
    uses: sede-open/openMCMC/.github/workflows/publish_docs.yml@main
    needs: Build
