# SPDX-FileCopyrightText: 2024 Shell Global Solutions International B.V. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: PullRequest

on:
  pull_request:
    types: [opened, synchronize, reopened, review_requested]
    branches:
      - main

jobs:
  CodeFormat:
    uses: sede-open/openMCMC/.github/workflows/code_formatting.yml@main
    secrets: inherit

  Pydocstyle:
    uses: sede-open/openMCMC/.github/workflows/pydocstyle_check.yml@main
    needs: CodeFormat

  Pylint:
    uses: sede-open/openMCMC/.github/workflows/pylint_check.yml@main
    needs: Pydocstyle

  Tests:
    uses: sede-open/openMCMC/.github/workflows/run_tests.yml@main
    needs: CodeFormat

  SonarCloud:
    uses: sede-open/openMCMC/.github/workflows/sonarcloud_analysis.yml@main
    needs: Tests
    secrets: inherit