# SPDX-FileCopyrightText: 2024 Shell Global Solutions International B.V. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: Run Pytest

on:
  workflow_call:

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest==7.4.4
          pip install pytest-cov
          pip install .
      - name: Unit test with pytest
        run: |
          pytest --cov-report=xml --junitxml=pytest_junit.xml
      - name: Fix code coverage paths
        run: |
          sed -i 's/\/opt\/hostedtoolcache\/Python\/.*\/site-packages/src/g' coverage.xml
          sed -i 's/opt\/hostedtoolcache\/Python\/.*\/site-packages/src/g' coverage.xml
          sed -i 's/\.opt\.hostedtoolcache\.Python\..*\.site-packages\.openmcmc/src/g' coverage.xml
          sed -i 's/opt\.hostedtoolcache\.Python\..*\.site-packages\.openmcmc/src/g' coverage.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
      - name: Upload coverage xml results
        uses: actions/upload-artifact@v4
        with:
          name: coverage_xml
          path: coverage.xml
        if: ${{ always() }}
      - name: Upload coverage junitxml results
        uses: actions/upload-artifact@v4
        with:
          name: pytest_junitxml
          path: pytest_junit.xml
        if: ${{ always() }}